const cars=[
 {id:1,name:'Maruti Suzuki Swift',type:'Hatchback',seats:5,gear:'Manual',perKm:12,icon:'🚗'},
 {id:2,name:'Hyundai Creta',type:'SUV',seats:5,gear:'Automatic',perKm:20,icon:'🚙'},
 {id:3,name:'Honda City',type:'Sedan',seats:5,gear:'Automatic',perKm:17,icon:'🚘'},
 {id:4,name:'Tata Nexon',type:'SUV',seats:5,gear:'Manual',perKm:18,icon:'🚙'},
 {id:5,name:'Maruti Baleno',type:'Hatchback',seats:5,gear:'Automatic',perKm:14,icon:'🚗'},
 {id:6,name:'Hyundai Verna',type:'Sedan',seats:5,gear:'Manual',perKm:16,icon:'🚘'}
];
const grid=document.querySelector('#carGrid'),toast=document.querySelector('#toast'),bookingDialog=document.querySelector('#bookingDialog'),adminDialog=document.querySelector('#adminDialog'),adminContent=document.querySelector('#adminContent'),loginDialog=document.querySelector('#loginDialog'),loginContent=document.querySelector('#loginContent'),pickupInput=document.querySelector('#pickup'),destinationInput=document.querySelector('#destination'),rentalDaysInput=document.querySelector('#rentalDays');
let selectedFilter='all',tripEstimate=null;
pickupInput.value=new Date().toISOString().split('T')[0];
const money=value=>`₹${Math.round(value).toLocaleString('en-IN')}`;
function renderCars(){grid.innerHTML=cars.filter(car=>selectedFilter==='all'||car.type===selectedFilter).map(car=>{const estimate=tripEstimate?money(car.perKm*tripEstimate.distance_km):null;return `<article class="car-card"><div class="vehicle-art">${car.icon}</div><div class="car-name"><div><h3>${car.name}</h3><span>${car.type}</span></div><span class="tag">Available</span></div><div class="specs"><span>👤 ${car.seats} seats</span><span>⚙ ${car.gear}</span></div><div class="price-row"><div><strong>${estimate||money(car.perKm)}</strong> <small>${estimate?'estimated trip':'/ km'}</small>${estimate?`<small><br>${tripEstimate.distance_km} km ${tripEstimate.source}</small>`:''}</div><button class="book-btn" data-book="${car.id}">Book now</button></div></article>`}).join('')}
renderCars();
document.querySelectorAll('.filter').forEach(button=>button.onclick=()=>{selectedFilter=button.dataset.filter;document.querySelectorAll('.filter').forEach(item=>item.classList.toggle('active',item===button));renderCars()});
function clearEstimate(){if(tripEstimate){tripEstimate=null;renderCars()}}
destinationInput.addEventListener('input',clearEstimate);document.querySelector('#location').addEventListener('input',clearEstimate);
document.querySelector('#searchForm').onsubmit=async event=>{event.preventDefault();if(Number(rentalDaysInput.value)<1)return say('Please enter at least one rental day.');try{const response=await fetch('/api/estimate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pickup:document.querySelector('#location').value,destination:destinationInput.value})});const result=await response.json();if(!response.ok)throw new Error(result.error);tripEstimate=result;renderCars();document.querySelector('#vehicles').scrollIntoView({behavior:'smooth'});say(`${result.distance_km} km ${result.source} found. Prices updated automatically.`)}catch(error){say(error.message||'Unable to estimate the distance. Please try again.')}};
grid.onclick=event=>{const id=event.target.dataset.book;if(id)openBooking(cars.find(car=>car.id==id))};
function openBooking(car){if(!tripEstimate)return say('Enter the locations and click Find a car to calculate the route price first.');const days=Math.max(1,Number(rentalDaysInput.value)||1),amount=car.perKm*tripEstimate.distance_km,endDate=new Date(`${pickupInput.value}T00:00:00`);endDate.setDate(endDate.getDate()+days);const returnDate=endDate.toISOString().split('T')[0];document.querySelector('#bookingContent').innerHTML=`<form class="booking" id="reserveForm"><p class="eyebrow">COMPLETE YOUR RESERVATION</p><h2>Book ${car.name}</h2><p>Price calculated from the estimated road distance.</p><div class="summary"><span>${document.querySelector('#location').value} → ${destinationInput.value}<br><small>${tripEstimate.distance_km} km · ${days} day${days>1?'s':''} · ₹${car.perKm}/km</small></span><strong>${money(amount)}</strong></div><div class="form-grid"><label>Full name<input name="customer" required placeholder="Your name"></label><label>Phone number<input name="phone" required pattern="[0-9]{10}" placeholder="10-digit mobile number"></label><label>Email address<input name="email" required type="email" placeholder="you@example.com"></label><label>Payment method<select><option>UPI / Card</option><option>Pay at pickup</option></select></label></div><button class="primary pay">Confirm & pay ${money(amount)} →</button></form>`;bookingDialog.showModal();document.querySelector('#reserveForm').onsubmit=async event=>{event.preventDefault();const form=new FormData(event.target);try{const response=await fetch('/api/bookings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({customer:form.get('customer'),phone:form.get('phone'),email:form.get('email'),car:car.name,rental_dates:`${pickupInput.value} to ${returnDate} (${tripEstimate.distance_km} km)`,amount:Math.round(amount)})});if(!response.ok)throw new Error();document.querySelector('#bookingContent').innerHTML=`<div class="confirmation"><div class="check">✓</div><p class="eyebrow">BOOKING CONFIRMED</p><h2>Your ride is reserved!</h2><p>Your confirmation has been created. Please bring your licence and booking reference at pick-up.</p><button class="primary" onclick="document.querySelector('#bookingDialog').close()">Done</button></div>`;say('Booking confirmed — it is saved in the admin portal.')}catch{say('Could not save this booking. Start the Python server and try again.')}}}
function say(message){toast.textContent=message;toast.className='show';setTimeout(()=>toast.className='',3500)}
document.querySelectorAll('[data-close]').forEach(button=>button.onclick=()=>document.querySelector('#'+button.dataset.close).close());
document.querySelector('#adminOpen').onclick=async()=>{let bookings=[];try{bookings=await (await fetch('/api/bookings')).json()}catch{say('Start the Python server to open the live dashboard.');return}adminContent.innerHTML=`<section class="admin"><div class="admin-top"><div><p class="eyebrow">MANAGEMENT CONSOLE</p><h2>Booking dashboard</h2></div><div><span class="admin-stat">${bookings.length}</span> reservations</div></div>${bookings.length?`<table><thead><tr><th>Customer</th><th>Vehicle</th><th>Rental dates</th><th>Amount</th><th>Status</th></tr></thead><tbody>${bookings.map(item=>`<tr><td>${item.customer}</td><td>${item.car}</td><td>${item.rental_dates}</td><td>${money(item.amount)}</td><td><span class="status">CONFIRMED</span></td></tr>`).join('')}</tbody></table><button class="danger" id="clearBookings">Clear demo data</button>`:'<p class="empty">No reservations yet. New customer bookings will appear here automatically.</p>'}</section>`;adminDialog.showModal();document.querySelector('#clearBookings')?.addEventListener('click',async()=>{await fetch('/api/bookings',{method:'DELETE'});adminDialog.close();say('Demo bookings cleared.')})};
document.querySelector('#supportBtn').onclick=()=>say('Support request received. We’ll get back to you shortly!');
document.querySelector('#menuBtn').onclick=()=>say('Use “Explore cars” to find your next ride.');
let currentUser=JSON.parse(sessionStorage.getItem('roadlyUser')||'null');
const savedOpenBooking=openBooking;
function authHeaders(){const token=sessionStorage.getItem('roadlyToken');return token?{Authorization:`Bearer ${token}`}:{}}
function updateLoginButton(){document.querySelector('#loginOpen').textContent=currentUser?`Hi, ${currentUser.name.split(' ')[0]}`:'Login'}
function openLogin(role='customer'){loginContent.innerHTML=`<section class="auth"><p class="eyebrow">ACCOUNT ACCESS</p><h2>${role==='owner'?'Owner portal':'Customer portal'}</h2><div class="auth-tabs"><button class="${role==='customer'?'active':''}" id="customerTab">Customer</button><button class="${role==='owner'?'active':''}" id="ownerTab">Owner</button></div><form id="loginForm" class="form-grid"><label>Email<input name="email" type="email" required placeholder="you@example.com"></label><label>Password<input name="password" type="password" required placeholder="Your password"></label><button class="primary pay">Log in</button></form>${role==='customer'?`<p class="auth-note">New here? <button class="text-btn" id="registerOpen">Create a customer account</button></p>`:`<p class="auth-note">Demo owner: owner@roadly.com &middot; password: owner123</p>`}</section>`;loginDialog.showModal();document.querySelector('#customerTab').onclick=()=>openLogin('customer');document.querySelector('#ownerTab').onclick=()=>openLogin('owner');document.querySelector('#registerOpen')?.addEventListener('click',openRegister);document.querySelector('#loginForm').onsubmit=async event=>{event.preventDefault();const form=new FormData(event.target);const response=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:form.get('email'),password:form.get('password'),role})});const result=await response.json();if(!response.ok)return say(result.error);currentUser=result.user;sessionStorage.setItem('roadlyUser',JSON.stringify(result.user));sessionStorage.setItem('roadlyToken',result.token);loginDialog.close();updateLoginButton();say(`Welcome, ${result.user.name}!`)}}
function openRegister(){loginContent.innerHTML=`<section class="auth"><p class="eyebrow">CUSTOMER ACCOUNT</p><h2>Create an account</h2><form id="registerForm" class="form-grid"><label>Full name<input name="name" required placeholder="Your name"></label><label>Email<input name="email" type="email" required placeholder="you@example.com"></label><label>Password<input name="password" type="password" minlength="6" required placeholder="At least 6 characters"></label><button class="primary pay">Create account</button></form><p class="auth-note"><button class="text-btn" id="backLogin">Back to login</button></p></section>`;document.querySelector('#backLogin').onclick=()=>openLogin('customer');document.querySelector('#registerForm').onsubmit=async event=>{event.preventDefault();const form=new FormData(event.target);const response=await fetch('/api/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(form))});const result=await response.json();if(!response.ok)return say(result.error);say(result.message);openLogin('customer')}}
openBooking=car=>{if(!currentUser||currentUser.role!=='customer'){openLogin('customer');return say('Please log in as a customer before booking.')}savedOpenBooking(car)};
document.querySelector('#loginOpen').onclick=()=>currentUser?(()=>{sessionStorage.clear();currentUser=null;updateLoginButton();say('Logged out successfully.')})():openLogin('customer');
document.querySelector('#adminOpen').onclick=()=>{if(!currentUser||currentUser.role!=='owner')return openLogin('owner');adminContent.innerHTML='<p class="empty">Loading bookings…</p>';adminDialog.showModal();fetch('/api/bookings',{headers:authHeaders()}).then(response=>response.json()).then(bookings=>{adminContent.innerHTML=`<section class="admin"><div class="admin-top"><div><p class="eyebrow">OWNER CONSOLE</p><h2>Booking dashboard</h2></div><div><span class="admin-stat">${bookings.length}</span> reservations</div></div>${bookings.length?`<table><thead><tr><th>Customer</th><th>Vehicle</th><th>Rental dates</th><th>Amount</th><th>Status</th></tr></thead><tbody>${bookings.map(item=>`<tr><td>${item.customer}</td><td>${item.car}</td><td>${item.rental_dates}</td><td>${money(item.amount)}</td><td><span class="status">CONFIRMED</span></td></tr>`).join('')}</tbody></table>`:'<p class="empty">No reservations yet.</p>'}</section>`})};
updateLoginButton();
// Rental plan: the customer chooses the pricing method before every search.
const dailyRates=[1600,2800,2500,2300,1900,2200];
cars.forEach((car,index)=>car.dailyRate=dailyRates[index]);
let selectedPlan=null, planReady=false;
const destinationField=document.querySelector('#destinationField');
function updatePlanUI(){const distancePlan=selectedPlan==='distance';destinationField.hidden=selectedPlan==='daily';destinationInput.required=distancePlan;document.querySelectorAll('.plan-btn').forEach(button=>button.classList.toggle('active',button.dataset.plan===selectedPlan));}
document.querySelectorAll('.plan-btn').forEach(button=>button.onclick=()=>{selectedPlan=button.dataset.plan;tripEstimate=null;planReady=false;updatePlanUI();renderCars();say(selectedPlan==='distance'?'Distance pricing selected. Enter destination to calculate the route.':'Daily fixed-price rental selected. Enter the rental days.')});
function renderCars(){const days=Math.max(1,Number(rentalDaysInput.value)||1);grid.innerHTML=cars.filter(car=>selectedFilter==='all'||car.type===selectedFilter).map(car=>{let cost=money(car.perKm),caption='/ km',detail='';if(selectedPlan==='daily'){cost=planReady?money(car.dailyRate*days):money(car.dailyRate);caption=planReady?'fixed rental':'/ day';detail=planReady?`<small><br>${days} day${days>1?'s':''} fixed rental</small>`:''}else if(selectedPlan==='distance'&&tripEstimate){cost=money(car.perKm*tripEstimate.distance_km);caption='estimated trip';detail=`<small><br>${tripEstimate.distance_km} km ${tripEstimate.source}</small>`}return `<article class="car-card"><div class="vehicle-art">${car.icon}</div><div class="car-name"><div><h3>${car.name}</h3><span>${car.type}</span></div><span class="tag">Available</span></div><div class="specs"><span>👤 ${car.seats} seats</span><span>⚙ ${car.gear}</span></div><div class="price-row"><div><strong>${cost}</strong> <small>${caption}</small>${detail}</div><button class="book-btn" data-book="${car.id}">Book now</button></div></article>`}).join('')}
document.querySelector('#searchForm').onsubmit=async event=>{event.preventDefault();if(!selectedPlan)return say('Choose either distance-based or daily fixed-price rental first.');const days=Math.max(1,Number(rentalDaysInput.value)||1);if(selectedPlan==='daily'){planReady=true;tripEstimate=null;renderCars();document.querySelector('#vehicles').scrollIntoView({behavior:'smooth'});return say(`${days}-day fixed rental prices are ready.`)}try{const response=await fetch('/api/estimate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pickup:document.querySelector('#location').value,destination:destinationInput.value})});const result=await response.json();if(!response.ok)throw new Error(result.error);tripEstimate=result;planReady=true;renderCars();document.querySelector('#vehicles').scrollIntoView({behavior:'smooth'});say(`${result.distance_km} km ${result.source} found. Distance prices updated.`)}catch(error){say(error.message||'Unable to estimate the distance. Please try again.')}};
openBooking=car=>{if(!currentUser||currentUser.role!=='customer'){openLogin('customer');return say('Please log in as a customer before booking.')}if(!selectedPlan||!planReady)return say('Choose a rental option and click Find a car first.');const days=Math.max(1,Number(rentalDaysInput.value)||1);const isDaily=selectedPlan==='daily';const amount=isDaily?car.dailyRate*days:car.perKm*tripEstimate.distance_km;const endDate=new Date(`${pickupInput.value}T00:00:00`);endDate.setDate(endDate.getDate()+days);const returnDate=endDate.toISOString().split('T')[0];const summary=isDaily?`${days} day${days>1?'s':''} fixed rental · ₹${car.dailyRate}/day`:`${tripEstimate.distance_km} km · ₹${car.perKm}/km`;document.querySelector('#bookingContent').innerHTML=`<form class="booking" id="reserveForm"><p class="eyebrow">${isDaily?'DAILY FIXED-PRICE RENTAL':'DISTANCE-BASED RENTAL'}</p><h2>Book ${car.name}</h2><p>Review your ${isDaily?'daily fixed-price':'distance-based'} estimate.</p><div class="summary"><span>${document.querySelector('#location').value}${isDaily?'':` → ${destinationInput.value}`}<br><small>${summary}</small></span><strong>${money(amount)}</strong></div><div class="form-grid"><label>Full name<input name="customer" required placeholder="Your name"></label><label>Phone number<input name="phone" required pattern="[0-9]{10}" placeholder="10-digit mobile number"></label><label>Email address<input name="email" required type="email" placeholder="you@example.com"></label><label>Payment method<select><option>UPI / Card</option><option>Pay at pickup</option></select></label></div><button class="primary pay">Confirm & pay ${money(amount)} →</button></form>`;bookingDialog.showModal();document.querySelector('#reserveForm').onsubmit=async event=>{event.preventDefault();const form=new FormData(event.target);const response=await fetch('/api/bookings',{method:'POST',headers:{'Content-Type':'application/json',...authHeaders()},body:JSON.stringify({customer:form.get('customer'),phone:form.get('phone'),email:form.get('email'),car:car.name,rental_dates:`${pickupInput.value} to ${returnDate} (${isDaily?'daily fixed price':`${tripEstimate.distance_km} km`})`,amount:Math.round(amount)})});if(!response.ok)return say((await response.json()).error||'Booking failed.');document.querySelector('#bookingContent').innerHTML=`<div class="confirmation"><div class="check">✓</div><p class="eyebrow">BOOKING CONFIRMED</p><h2>Your ride is reserved!</h2><p>Your confirmation has been created.</p><button class="primary" onclick="document.querySelector('#bookingDialog').close()">Done</button></div>`;say('Booking confirmed — it is saved in the owner portal.')}};
updatePlanUI();renderCars();
